<!DOCTYPE html>
<html lang="en">
<head>
    <metli charset="UTF-8">
    <metli http-equiv="X-UA-Compatible" content="IE=edge">
    <metli name="../html_pdf/viewport" content="width=de../html_pdf/vice-width, initial-scale=1.0">
    <link rel="stylesheet" href="../Bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../style.css">
    <script src="../Bootstrap/js/bootstrap.min.js"></script> 
    <link rel="stylesheet" href="../css/foot_head.css">
    <link rel="stylesheet" href="../css/style_cgu_cgv.css">
    <title>Document</title>
</head>
<?php
    include("head.php");
?>
<body>
    <main>
        <section class="conteneur">
            <article class="detail_cgu_cgv">
                <ul href="#page">CGU
                    <li href="#page">1</li>
                    <li href="#page">2</li>
                    <li href="#page">3</li>
                    <li href="#page">4</li>
                    <li href="#page">5</li>
                </ul>
                <ul href="#page2">CGV
                    <li href="#page">1</li>
                    <li href="#page">2</li>
                    <li href="#page">3</li>
                    <li href="#page">4</li>
                    <li href="#page">5</li>
                </ul>
            </article>
            <hr class="separation">
            <section class="cgu_cgv">
                <article class="cgu">
                    <div style="position:absolute;top:0.62in;left:1.42in;width:6.22in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000">Conditions générales de vente de produits en ligne à des consommateurs particuliers</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:0.97in;left:0.43in;width:0.82in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000">Préambule</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:1.33in;left:0.43in;width:7.57in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Les présentes conditions générales de vente s’appliquent à toutes les ventes conclues sur le site internet Alizon.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:1.68in;left:0.43in;width:3.08in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Le site Internet alizon.com est un ser../html_pdf/vice de :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:2.04in;left:0.70in;width:0.13in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:2.04in;left:0.97in;width:3.50in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">La société Alizon</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">située 1 rue edouard Branly 22300 Lannion, France</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Adresse URL du site : alizon.bzh</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">e-mail : cobrec@alizon.bzh</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">numéro de téléphone : 0102030405</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">numéro d’immatriculation : 123456789</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:3.27in;left:0.43in;width:7.95in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Le site Internet Alizon commercialise les produits suivants : bols bretons, cirés jaune, cidre, crêpes, sardines, galettes.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Le </span></SPAN><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:0.26in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">client </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:0.70in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">déclare </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:1.28in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">avoir </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:1.70in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">pris </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:2.03in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">connaissance </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:3.04in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">et </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:3.26in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">avoir </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:3.67in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">accepté </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:4.29in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">les </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:4.57in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">conditions </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:5.34in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">générales </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:6.09in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">de </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:6.34in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">vente </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:6.78in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">antérieurement </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:7.88in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">à </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:3.62in;left:0.43in;width:8.20in;line-height:0.19in;"><DIV style="position:relative; left:8.04in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">la</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">passation de sa commande. La validation de la commande vaut donc acceptation des conditions générales de vente.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:4.15in;left:0.43in;width:4.30in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Ces CGV sont accessibles à tout moment sur le site alizon.bzh.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:4.51in;left:0.43in;width:1.39in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000">Article 1 - Contenu</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:4.87in;left:0.43in;width:8.19in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Les présentes conditions générales ont pour objet de définir les droits et obligations des parties dans le cadre de la vente</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">en ligne des biens proposés par le vendeur à l’acheteur, à partir du site internet Alizon.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Les </span></SPAN><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:0.33in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">présentes </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:1.08in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">conditions </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:1.84in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">ne </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:2.09in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">concernent </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:2.91in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">que </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:3.24in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">les </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:3.51in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">achats </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:4.03in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">effectués </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:4.72in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">sur </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:5.01in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">le </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:5.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">site </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:5.51in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">de </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:5.76in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Alizon </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:6.25in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">et </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:6.85in;line-height:0.20in;"><DIV style="position:relative; left:6.45in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">livrés</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></DIV></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:6.96in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">exclusivement </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:5.40in;left:0.43in;width:8.20in;line-height:0.19in;"><DIV style="position:relative; left:7.99in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">en</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">métropole ou en Corse. Pour toute livraison dans les DROM-COM ou à l’etranger, il con../html_pdf/vient d’adresser un </span></SPAN><br/></div>
                    <div style="position:absolute;top:5.57in;left:0.43in;width:8.20in;line-height:0.19in;"><DIV style="position:relative; left:7.41in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">message à</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">l’adresse suivante : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#1155cc">cobrec@alizon.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">bzh.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:6.10in;left:0.43in;width:7.04in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Ces achats concernent les produits suivants : bols bretons, cirés jaune, cidre, crêpes, sardines, galettes.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:6.46in;left:0.43in;width:2.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000">Article 2 - Modalités de règlement :</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:6.81in;left:0.43in;width:5.57in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Nous acceptons les moyens de paiement suivants : ( cartes, bon d’achat, paypal ).</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:7.17in;left:0.43in;width:4.38in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Nous ne pratiquons pas l’escompte en cas de paiement anticipé.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:7.53in;left:0.43in;width:3.47in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000">Article 3 - Protection des données personnelles</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:7.88in;left:0.43in;width:1.36in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Données collectées</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:8.24in;left:0.43in;width:5.77in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Les données à caractère personnel qui sont collectées sur ce site sont les suivantes :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:8.59in;left:0.70in;width:0.13in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:8.59in;left:0.97in;width:7.60in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">ouverture du compte : lors de la création du compte de l’utilisateur, ses nom, prénom, adresse électronique, n°de</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">téléphone, adresse postale.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:8.94in;left:0.70in;width:0.13in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:8.94in;left:0.97in;width:7.50in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Connexion : lors de la connexion de l’utilisateur au site web, celui-ci enregistre, notamment, ses noms, prénom,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">données de connexion, d’utilisation, de localisation et ses données relatives au paiement.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:9.29in;left:0.70in;width:0.13in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:9.29in;left:0.97in;width:7.45in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Profil : L’utilisation des prestations prévues sur le site web permet de renseigner un profil, pouvant comprendre</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">une adresse et un numéro de téléphone.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:9.64in;left:0.70in;width:0.13in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:9.64in;left:0.97in;width:7.64in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Paiement : dans le cadre du paiement des produits et prestations proposés sur le site web, celui-ci enregistre des</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">données financières relatives au compte bancaire ou à la carte de crédit de l’utilisateur.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:9.99in;left:0.70in;width:0.13in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">●</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:9.99in;left:0.97in;width:7.47in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Cookies : les cookies sont utilisés dans le cadre de l’utilisation du site. L’utilisateur a la possibilité de désactiver</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">les cookies à partir des paramètres de son na../html_pdf/vigateur.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:10.52in;left:0.43in;width:1.06in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000">Article 4 - Prix</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:10.87in;left:0.43in;width:8.19in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Le vendeur se réserve le droit de modifier ses prix à tout moment mais s’engage à appliquer les tarifs en ../html_pdf/vigueur indiqués</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">au moment de la commande, sous réserve de disponibilité à cette date.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">Les </span></SPAN><br/></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:0.32in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">prix </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:0.64in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">unitaires </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:1.29in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">sont </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:1.65in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">indiqués </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:2.29in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">en </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:2.54in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">euros, </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.20in;"><DIV style="position:relative; left:3.03in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">HT </span></SPAN></DIV><br/></div>
                    <div style="position:absolute;top:11.40in;left:0.43in;width:8.20in;line-height:0.18in;"><DIV style="position:relative; left:3.31in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">et TTC. Ils ne tiennent pas compte des frais de livraison, facturés en</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">supplément, et indiqués avant la validation de la commande. Les prix tiennent compte de la TVA applicable au jour de la</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">commande et tout changement du taux applicable TVA sera automatiquement répercuté sur le prix des produits de la</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000">boutique en ligne.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Arial;color:#000000"> </span><br/></SPAN></div>
                    <img style="position:absolute;top:5.89in;left:1.77in;width:1.06in;height:0.02in" src="../html_pdf/vi_46.png" /></article>
                <article class="cgv"></article>        
            </section>
        </section>
    </main>
</body>
<footer>
<?php
    include("footer.php");
?>
</footer>
</html>
